FROM python:3.10-slim

# Встановлюємо робочу директорію в контейнері
WORKDIR /app

# Копіюємо файл залежностей у контейнер
COPY requirements.txt requirements.txt

# Встановлюємо необхідні залежності
RUN pip install -r requirements.txt

# Копіюємо всі файли нашого застосунку в робочу директорію
COPY . .

# Відкриваємо порт 5000
EXPOSE 5000

# Вказуємо команду для запуску застосунку
CMD ["python", "app.py"]
